nightfrost_hostname: nightfrost

nightfrost_user: nightfrost
nightfrost_group: nightfrost
nightfrost_root: /opt/nightfrost
nightfrost_config_dir: /etc/nightfrost
nightfrost_explorer_root: /usr/share/nginx/html/nightfrost
nightfrost_landing_root: /usr/share/nginx/html/nightfrost-landing
nightfrost_docs_root: /usr/share/nginx/html/nightfrost-docs

nightfrost_indexers:
  - network: preview
    node_url: wss://rpc.preview.midnight.network
    listen_port: 3101
    hostname: preview.nightfrost.dev
  - network: mainnet
    node_url: wss://rpc.mainnet.midnight.network
    listen_port: 3102
    hostname: mainnet.nightfrost.dev
  - network: preprod
    node_url: wss://rpc.preprod.midnight.network
    listen_port: 3103
    hostname: preprod.nightfrost.dev
